### ISSUE TITLE
Failed to build site locally.

### ISSUE THREAD

**Issue by Credhat** [y1cunhui/uniswapV3-book-zh-cn#6]
root in ~/vscode/books/uniswapV3-book-zh-cn                                                                                                                             │≥ sudo /snap/bin/hugo server -D                                                                        │Watching for changes in /root/vscode/books/uniswapV3-book-zh-cn/{archetypes,cont                                                                                        │ent,static}                                                                                                                                                             │Watching for config changes in /root/vscode/books/uniswapV3-book-zh-cn/config.to                                                                                        │ml
│Start building sites …                                                                                                                                                  │hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=snap:0.124.1                                                                                                                      
│Built in 8 ms                                                                                                                                                           │Error: error building site: process: readAndProcessContent: "/root/vscode/books/                                                                                        │uniswapV3-book-zh-cn/content/docs/milestone_1/first-swap.md:12:1": failed to ext                                                                                        │ract shortcode: template for shortcode "katex" not found 

看起来是 katex 没能正确找到.. 但是我不知道怎么解决. 请问有什么解决办法吗?
至于我为什么要本地渲染. 是因为我想要看看本地渲染能否实现将教程导出为 pdf.

![image](https://github.com/y1cunhui/uniswapV3-book-zh-cn/assets/28824415/bf1f10a2-f165-4e95-9d58-83235643efc7)

**Comment by ryang-max** [comment]
这个应该属于hugo框架相关问题，我也不太懂仅做了内容翻译。hugo的issue下有一些关于生成pdf的讨论你可以参考
